---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
implicit:
  - Пользователи ожидают интуитивно понятный интерфейс, который позволяет легко находить нужные товары
  - Быстрая загрузка сайта критически важна для удержания пользователей и снижения показателя отказов
  - Удобство выбора способа оплаты является важным фактором для покупателей
  - Информация о сроках и стоимости доставки должна быть четкой и доступной
  - Возможность оставлять отзывы и видеть мнения других покупателей помогает пользователям принимать решения о покупке
  - Рекомендации на основе предыдущих покупок или просмотров могут улучшить пользовательский опыт
